language: node_js
node_js:
  - '12'
dist: trusty
sudo: required
notifications:
  slack: prepperlearning:VgHyCXQ8lq11Qonx7OFYEGoA
branches:
  only:
    - staging
install:
  - npm install
script:
  - npm run lint
  - npm run set-env
  - cat env/.env
  - npm run test
  - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] ; then
  npm run clean;
  npm run build
  ; fi'
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: KEvh/mUGg+Q8w74Y8Xu5W4WQVRn7jcj+TadnwgZYGYdmNLk52gTm40k4ueYyzkxf8puVDKOJO2Lu1Y/quW+LMKbNmLFtZw0qAW7GWCnA8lvVxLlVgK884NikBeiFtuUY1Sdyj8y7SoatF1PJluqyTm2hKT1XZWtkF7kTo7+lRjd6v8ru/nqL8AaCpebUsV24e+gBWOXRZ7kclgWrzFwSRIgFJ23ZV5Q8uWrf9tVLt0TiSSoAGKolpkF7ufRCxju8H5j9msjh1JnVb4czeG6Ii5lWhDGovKK7W8/wd3VGjjDt3hW0YB3SkHR6x+UW5XY4q/I8AY5ggn7Cf4RSfSQOaxwLKw/JqNAfBWs52WDlY9Wue19S/xzB9tEJ6tfOZQ9lql4ziffk9IxmUb0Aybl4yUFvAA7ks37pqD3otetD97SvA/4Ndh0ZVAt/xLgYYVeR84/ihfmYCIvmtk0KJ78Vqp+VBhF/fz8yHkpHEG1FtaXUeV51JdWGW5baC6Kav2R53G5plpUVAzXsBb5v68cb+7X/V2fEIMrDL3ib8WndIFBmzNh8j4Nn3Sg74WYdRaUhZEmkHYP4QcwZ9l5UYSx9s+q9cJrl+mfad+15uUTS1TwuSBtCyddWJY9STLxF3QFrM5CidnUD3edQToHFreJVt5mv88+h9HN7cfYvDdnZm8U=
  on:
    branch: staging
