language: node_js
node_js:
  - '12'
dist: trusty
sudo: required
notifications:
  slack: prepperlearning:VgHyCXQ8lq11Qonx7OFYEGoA
branches:
  only:
    - staging
install:
  - npm install
script:
  - npm run lint
  - npm run set-env
  - cat env/.env
  - npm run test
  - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] ; then
  npm run clean;
  npm run build
  ; fi'
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  on:
    branch: staging
